kind: live
id: mlflow_action
title: mlflow-action

volumes:
  mlflow_artifacts:
    remote: storage:${{ flow.flow_id }}/mlflow_artifacts
    mount: /usr/local/share/mlflow

jobs:
  mlflow_server:
    action: gh:neuro-actions/mlflow@v1.17.0
    args:
      backend_store_uri: sqlite:///${{ volumes.mlflow_artifacts.mount }}/mlflow.db
      default_artifact_root: ${{ volumes.mlflow_artifacts.mount }}
      volumes: "${{ to_json( [volumes.mlflow_artifacts.ref_rw] ) }}"
