kind: live
id: mlflow_action
title: mlflow-action

volumes:
  mlflow_artifacts:
    remote: storage:${{ flow.flow_id }}/mlflow_artifacts
    mount: /usr/local/share/mlflow

jobs:
  mlflow_server:
    action: gh:neuro-actions/mlflow@master
    args:
      backend_store_uri: sqlite:////${{ volumes.mlflow_artifacts.mount }}/mlflow.db 
      artifacts_destination: ${{ volumes.mlflow_artifacts.mount }}
      volumes: "${{ to_json( [volumes.mlflow_artifacts.ref_rw] ) }}"
