name: CI

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t "ghcr.io/neuro-inc/mlflow:${{ github.event.release.tag_name }}" .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/neuro-inc/mlflow:${{ github.event.release.tag_name }}

      - name: Tag Docker Image for platform-pipelines
        run: |
          docker tag ghcr.io/neuro-inc/mlflow:${{ github.event.release.tag_name }} ghcr.io/neuro-inc/mlflow:pipelines
