name: CI

on:
  pull_request:
    branches: ["main"]
  pull_request_target:
    branches: ["main"]
  workflow_call: {}
  workflow_dispatch: {}
jobs:
  test:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      local: true
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCRIO_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: github.event_name == 'pull_request'
        uses: docker/metadata-action@v4
        with:
            images: ghcr.io/apolo-actions/mlflow
            tags: |
              type=ref,event=pr
      - name: Build Docker Image
        run: |
          docker build -t "ghcr.io/apolo-actions/mlflow:development" .

      - name: Test image
        run: |
          make run-tests IMAGE_TAG=development IMAGE_NAME=ghcr.io/apolo-actions/mlflow

      - name: Push Docker Image
        run: |
          docker tag ghcr.io/apolo-actions/mlflow:development ${{ steps.meta.outputs.tags }}
          docker push ${{ steps.meta.outputs.tags }}

