name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      local: true
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t "ghcr.io/neuro-inc/mlflow:development" .

      - name: Test image
        run: |
          make test IMAGE_TAG=development IMAGE_NAME=ghcr.io/neuro-inc/mlflow

